#!/command/with-contenv bash

set -x

if [ $USENGINX -eq 1 ] ; then
    echo creating /etc/s6-overlay/s6-rc.d/user/contents.d/nginx
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/nginx
else
  echo not enabling nginx since USENGINX=$USENGINX
fi

if [ $USEHAPROXY -eq 1 ] ; then
    echo creating /etc/s6-overlay/s6-rc.d/user/contents.d/haproxy
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/haproxy
else
  echo not enabling haproxy since USEHAPROXY=$USEHAPROXY
fi