#!/command/with-contenv bash

echo EXECUTING s6-rc.d/haproxy/run

if [ -e /etc/haproxy/haproxy.cfg.pre ] ; then
  HAPROXYACCEPT=""
  if [ $HAPROXYACCEPTPROXY -eq 1 ] ; then
    HAPROXYACCEPT="accept-proxy"
  fi
  export HAPROXYACCEPT
  cat /etc/haproxy/haproxy.cfg.pre | envsubst > /etc/haproxy/haproxy.cfg
fi

if [ $USEHAPROXY -eq 0 ] ; then
  echo s6-rc.d/haproxy/run: USEHAPROXY is disabled - running dummy...
  tail -f /dev/null
else
  haproxy -- /etc/haproxy/haproxy.cfg
fi